### ISSUE TITLE
Error with missing Sites module

### ISSUE THREAD

**Issue by kontur** [praekelt/django-category#11]
As beginner to Django it took me a few moments to figure out why the package wasn't working. The Sites module is optional, however this category packages relies on it being install or else the [definitions in model](https://github.com/praekelt/django-category/blob/develop/category/models.py#L32) fail.

I suggest making this dependency / linking optional or mentioning it more explicitly. Simply adding `'django.contrib.sites'` to the `INSTALLED_APPS` in `settings.py` and defining `SITE_ID = 1` suffices to get the package working.

**Comment by qoda** [comment]
Thanks for the suggestion, we have included this in the README. Fixed in PR https://github.com/praekelt/django-category/pull/12
