### ISSUE TITLE
Sub category display issue

### ISSUE THREAD

**Issue by ratt** [praekelt/django-category#4]
When adding new categories to a sub category: EG

News -> Lifestyle -> sub sub category

When you display the categories list in the parent select box as well as in meta blocks of posts it lists each "sub sub category" as its parent name instead of its own name. So basically the list starts to look like:

News 
Lifestyle
Lifestyle
Lifestyle 

When it should be 
News 
Lifestyle
Sub Sub Category 
etc

**Comment by zarinpy** [comment]
Hi 
what is your query>

**Comment by cblignaut** [comment]
I'm closing this issue for now. Please, feel free to add a pull request for such a feature.
