### ISSUE TITLE
(WARNING) null has no effect on ManyToManyField

### ISSUE THREAD

**Issue by Chayemor** [praekelt/django-category#8]
Python 2.7.10
Django 1.11.3

My model:

```
class Post(models.Model):
    ...
    categories = models.ManyToManyField('category.Category', help_text='Taxonomy')
    tags = models.ManyToManyField('category.Tag', help_text='Tag', blank=False)
```

But whenever I hit the command `makemigrations` or `migrate` I get the following error on console:

`WARNINGS:
category.Category.sites: (fields.W340) null has no effect on ManyToManyField
category.Tag.categories: (fields.w340) null has no effect on ManyToManyField`

Have I done something wrong?

**Comment by kontur** [comment]
Even without any model definitions, simply by adding the package I get those same warnings:

> 
> WARNINGS:
> category.Category.sites: (fields.W340) null has no effect on ManyToManyField.
> category.Tag.categories: (fields.W340) null has no effect on ManyToManyField.

**Comment by cblignaut** [comment]
Thank you, the Warnings should be removed in the latest release
